import pandas as pd

new_data = [
    {
        "essay": "Título: O Impacto da Inteligência Artificial no Mercado de Trabalho\n\nA crescente integração da inteligência artificial (IA) nos processos produtivos levanta debates cruciais sobre o futuro do trabalho. Se por um lado a automação impulsiona a eficiência, por outro, ameaça postos de trabalho tradicionais. Nesse cenário, é imperativo que haja políticas de requalificação profissional e uma regulamentação ética que garanta uma transição justa.\n\nPrimeiramente, deve-se pontuar que a substituição de mão de obra humana por algoritmos já é uma realidade em setores como manufatura e atendimento. Contudo, essa mudança não significa necessariamente o fim do trabalho, mas a sua transformação. Segundo especialistas em economia digital, novas demandas surgirão, exigindo habilidades essencialmente humanas, como criatividade e empatia. Portanto, o grande desafio reside não em frear a tecnologia, mas em adaptar a força de trabalho às novas exigências.\n\nAdemais, a ausência de intervenção estatal nesse processo pode agravar a desigualdade socioeconômica. Sem acesso a uma educação voltada para o letramento digital, camadas mais vulneráveis da população correm o risco de exclusão estrutural do mercado. Logo, o Estado deve atuar como mediador, promovendo o ensino tecnológico em larga escala desde a educação básica, a fim de mitigar tais disparidades.\n\nEm suma, a inteligência artificial não deve ser vista apenas como uma ameaça, mas como um catalisador de transformações necessárias. Para que seus benefícios atinjam toda a sociedade, urge que o governo e o setor privado invistam massivamente em programas de capacitação continuada. Somente assim será possível aliar progresso tecnológico e justiça social.",
        "tema": 2.0, "tipo_texto": 2.0, "coerencia": 2.0, "coesao": 2.0, "modalidade": 2.0, "score": 10.0
    },
    {
        "essay": "Mobilidade Urbana: Um Desafio Contemporâneo\n\nNas últimas décadas, o crescimento desordenado das cidades brasileiras tem agravado severamente o problema da mobilidade urbana. O inchaço populacional somado à falta de planejamento resultou em congestionamentos diários e na precarização do transporte público. Para solucionar esse impasse, é necessária uma mudança no modelo de deslocamento urbano, priorizando a sustentabilidade e a coletividade.\n\nEm primeiro lugar, nota-se que o incentivo histórico ao uso do automóvel particular é um dos principais causadores do colapso no trânsito. Essa política, motivada por interesses econômicos da indústria automobilística, preteriu o investimento em modais como trens e metrôs. Como consequência, o trabalhador gasta horas no trânsito, o que afeta diretamente sua qualidade de vida e produtividade.\n\nAlém disso, o transporte público atual, na maioria das metrópoles, é caracterizado pela superlotação e tarifas elevadas. Isso afasta o cidadão e o obriga a buscar alternativas muitas vezes inviáveis, como o transporte clandestino. Se houvesse maior subsídio estatal, aliado à integração entre os diferentes meios de transporte, o sistema poderia se tornar mais atrativo e eficiente.\n\nPortanto, é preciso repensar a lógica de ocupação das cidades. O poder público deve direcionar investimentos pesados na ampliação e modernização da malha metroviária, além de construir ciclovias seguras. Dessa forma, as cidades poderão oferecer um fluxo mais dinâmico e democrático, garantindo o direito de ir e vir com dignidade.",
        "tema": 1.8, "tipo_texto": 2.0, "coerencia": 1.8, "coesao": 1.9, "modalidade": 1.8, "score": 9.3
    },
    {
        "essay": "Os desafios da saúde mental na era digital\n\nAtualmente a internet faz parte da vida de todo mundo. As redes sociais são usadas o tempo todo e isso tem trazido problemas pra saúde mental das pessoas, principalmente os jovens que passam o dia inteiro no celular. Por isso, a ansiedade e depressão tem aumentado bastante.\n\nÉ evidente que a comparação com a vida perfeita da internet faz mal. As pessoas postam apenas coisas boas e os jovens acham que a vida deles é ruim por causa disso. Além disso, o cyberbullying é um grande problema, porque as pessoas ofendem as outras escondidas atrás da tela e isso causa muitos danos psicológicos para as vitimas.\n\nPorém, não podemos dizer que a tecnologia é totalmente ruim. Existem aplicativos que ajudam as pessoas a meditar e até psicólogos online que facilitam o acesso. Mas ainda sim, o uso excessivo é perigoso e tem que ser controlado pelos pais quando se trata de adolescentes.\n\nEntão, para melhorar essa situação, as escolas deviam ter palestras sobre como usar a internet de forma segura. Também é preciso que os pais fiquem mais de olho no que os filhos fazem no celular. Assim a gente consegue diminuir os problemas de saúde mental na juventude.",
        "tema": 1.5, "tipo_texto": 1.5, "coerencia": 1.6, "coesao": 1.4, "modalidade": 1.3, "score": 7.3
    },
    {
        "essay": "A violência nos estádios\n\nO futebol é uma paixão nacional, mas a violência nos estádios estragam o esporte. Muitas brigas acontecem porque as torcidas organizadas marcam de brigar antes dos jogos e a polícia as vezes não consegue controlar todo mundo.\n\nIsso é muito ruim porque afasta as famílias dos campos. Antigamente os pais levavam os filhos pra assistir aos jogos mas hoje em dia é muito perigoso. O governo deveria colocar leis mais severas pra quem faz essas coisas. Também os clubes deviam ser punidos se os torcedores deles brigassem, pra ver se eles ajudam a fiscalizar melhor.\n\nAte porque o futebol tem que ser um lugar de paz e diversão. Se continuar assim, os estadios vão ficar vazios. Portanto, a policia tem que prender os brigões e os clubes banir eles pra sempre dos jogos, resolvendo assim o problema.",
        "tema": 1.4, "tipo_texto": 1.2, "coerencia": 1.3, "coesao": 1.0, "modalidade": 1.0, "score": 5.9
    },
    {
        "essay": "O meio ambiente\n\nO meio ambiente é importante para sobrevivermos e a poluição tá destruindo tudo. O aquecimento global faz muito calor e as geleiras tão derretendo.\n\nAs empresas poluem os rios jogando lixo, e as pessoas também jogam lixo na rua que entope bueiro e da enchente. A gente tem que reciclar o lixo pra não sujar o planeta. Outra coisa que faz mal é desmatamento das arvores, por que os animais ficam sem casa e morrem. As florestas dao oxigenio pra nos respirar, entao nao pode cortar elas.\n\nConcluindo que todo mundo tem que ajudar o planeta. Se cada um fizer sua parte a natureza vai agradecer e nois vamos ter um mundo melhor.",
        "tema": 1.0, "tipo_texto": 1.0, "coerencia": 1.0, "coesao": 0.8, "modalidade": 0.8, "score": 4.6
    },
    {
        "essay": "Redes socias\n\nas rede social e legal para falar cos amigo mas as veiz atrapalha o estudo. fica la o dia todo no face ou no insta e esquece de fazer tarefa.\n\ndevemos usar pouco. o celular vicia igual droga. tem q ter limite. as pessoas xingam muito tambem na internet pq ninguem ve o rosto do outro ai cria confusao atoa e os pais nem sabe.\n\npor isso acho q os dono do site devia blockear quem xinga. e ter mais propaganda de educacao na internet pro povo aprender a ter respeito.",
        "tema": 0.8, "tipo_texto": 0.7, "coerencia": 0.8, "coesao": 0.6, "modalidade": 0.5, "score": 3.4
    },
    {
        "essay": "Educação Financeira nas Escolas: Uma Necessidade Urgente\n\nA ausência de educação financeira no currículo escolar brasileiro reflete uma grave falha na formação do cidadão. Sem o preparo adequado para lidar com o dinheiro, grande parte dos jovens ingressa na vida adulta vulnerável ao endividamento precoce e à má gestão de recursos. Dessa forma, a inclusão dessa disciplina é fundamental para construir uma sociedade mais consciente e estável economicamente.\n\nEm princípio, cabe destacar que a falta de planejamento financeiro é uma realidade cultural no Brasil. Historicamente, o debate sobre dinheiro é tratado como tabu nos lares, o que faz com que o conhecimento chegue, muitas vezes, apenas na forma de juros bancários. Segundo dados de instituições de crédito, o número de inadimplentes no país bate recordes anuais. Isso evidencia que ensinar o jovem a poupar e investir não é um luxo, mas uma medida de prevenção contra o caos econômico pessoal.\n\nAlém disso, a educação financeira nas escolas atua como um forte equalizador social. Quando estudantes de escolas públicas aprendem a administrar pequenas quantias e compreendem conceitos básicos como juros compostos e inflação, eles ganham ferramentas para romper com o ciclo de pobreza familiar. Em contrapartida, a manutenção da ignorância sobre o tema perpetua a dependência de créditos abusivos e o superendividamento.\n\nPor conseguinte, o Ministério da Educação deve integrar a educação financeira à Base Nacional Comum Curricular (BNCC), de forma prática e interdisciplinar. Isso pode ser feito através de oficinas e projetos que simulem situações do cotidiano, contando com a capacitação dos professores da rede pública. Dessa maneira, estaremos formando adultos capazes de tomar decisões assertivas, fortalecendo não só suas vidas, mas também a economia do país como um todo.",
        "tema": 2.0, "tipo_texto": 2.0, "coerencia": 2.0, "coesao": 1.9, "modalidade": 2.0, "score": 9.9
    },
    {
        "essay": "A importância da leitura\n\nLer livros é essencial pro ser humano. Quem lê escreve melhor e sabe falar direito. No Brasil o povo não tem o costume de ler e isso é muito triste porque os livros tem bastante conhecimento pra vida.\n\nUm dos problemas é o preço dos livros, que são caros, e as bibliotecas não existem em toda cidade, principalmente no interior. Além disso agora com o celular ninguém quer ler um livro de papel. As crianças preferem jogar videogame ou assistir vídeo do que ler uma historinha.\n\nMas ler desenvolve a imaginação. O governo podia abaixar o imposto do livro, fazer campanha na televisão e criar mais bibliotecas públicas pros jovens. Assim mais gente vai ter acesso e o pais vai ser mais culto e inteligente.",
        "tema": 1.5, "tipo_texto": 1.6, "coerencia": 1.5, "coesao": 1.4, "modalidade": 1.5, "score": 7.5
    },
    {
        "essay": "Lixo espacial\n\nNos mandamos muito foguetes pro espaço e acaba deixando um monte de lixo la em cima de satelite velho e peça que solta. e perigoso porque pode bater na estacao espacial e estragar tudo.\n\nnem todos paises se preocupam com isso. as vezes cai uns pedaço na terra e asusta as pessoa mas gracas a deus ate hj nao machucou ninguem. devia ter uma faxina no espaco para catar tudo. \n\nassim o ceu fica limpo de novo e evita acidente grande no futuro. os paises q mandam foguetes tem que paga pela faxina.",
        "tema": 1.2, "tipo_texto": 1.0, "coerencia": 1.2, "coesao": 0.8, "modalidade": 0.8, "score": 5.0
    },
    {
        "essay": "O que eu acho do esporte\n\nEu gosto de jogar bola na rua com meus amigos e acho q esporte fas bem pro corpo pq as pessoa ficam fortes e saudaveis e nao ficam duentes atoa.\n\ntinha q ter quadras boas em todas pracas pra mininada joga pq senao eles fica fazendo coisa errada na rua e se envolve com crime. no meu barrio a quadra ta toda quebrada sem rede e sem luz. \n\ne bom o prefeito arruma a praca logo pra nois jogar.",
        "tema": 0.9, "tipo_texto": 0.8, "coerencia": 1.0, "coesao": 0.7, "modalidade": 0.6, "score": 4.0
    }
]

df_new = pd.DataFrame(new_data)
# Lendo o CSV atual (tratando possiveis encoding errors com utf-8)
df_old = pd.read_csv("data/redacoes_padrao.csv", encoding="utf-8")

df_final = pd.concat([df_old, df_new], ignore_index=True)
df_final.to_csv("data/redacoes_padrao.csv", index=False, encoding="utf-8")
print(f"Added {len(new_data)} new essays. Total is now {len(df_final)}.")
